# Generated by Django 3.2 on 2021-04-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rent_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rent',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
