# Generated by Django 3.2 on 2021-04-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_rent_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
