# Generated by Django 3.2 on 2021-04-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_rent_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('R', 'regular'), ('F', 'fiction'), ('N', 'novels')], default='R', max_length=1),
        ),
    ]
